import "./globals.css";
import AllProductsProvider from "../context/AllProductsProvider";
import CategoryProvider from "../context/CategoryProvider";
import NewProductProvider from "../context/NewProductProvider";
import Header from "../components/home/Header";
import FooterSection from "../components/home/FooterSection";
import React from "react";

export const metadata = {
  title: "e-shop",
  description: "Generated by create next app",
  icon: "/vercel.svg",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AllProductsProvider>
          <CategoryProvider>
            <NewProductProvider>
              <Header />
              {children}
              <FooterSection />
            </NewProductProvider>
          </CategoryProvider>
        </AllProductsProvider>
      </body>
    </html>
  );
}
